Repository ornikar/eslint-configs, pull requests merged in 2021-12, with the labels that each got.

#182 fix: disable unicorn/prefer-at for node [no issue]
  @ornikar/eslint-config/rules/node-override.js
Labels: :ok_hand: code/approved, :soon: automerge

#178 refactor(eslint-config): update to main branch of eslint-plugin-unicorn in comments [no issue]
  @ornikar/eslint-config/rules/unicorn.js
Labels: :ok_hand: code/approved, :soon: automerge

#196 feat(eslint-config): enable unicorn/no-new-array [no issue]
  @ornikar/eslint-config/rules/unicorn.js
  @ornikar/eslint-config/tests/no-new-array.js
Labels: :ok_hand: code/approved, frontend, :soon: automerge

#197 feat(eslint-config): enable unicorn/prefer-object-from-entries [no issue]
  @ornikar/eslint-config/rules/unicorn.js
  @ornikar/eslint-config/tests/prefer-object-from-entries.js
Labels: :ok_hand: code/approved, frontend, :soon: automerge

#198 fix(eslint-config-typescript): no unsafe argument as warn [no issue]
  @ornikar/eslint-config-typescript/rules/typescript-eslint.js
Labels: :ok_hand: code/approved, frontend, :soon: automerge

#199 fix(eslint-config-react): stop overriding react/sort-comp [no issue]
  @ornikar/eslint-config-react/rules/react.js
Labels: :ok_hand: code/approved, frontend, :soon: automerge

#202 feat: add stories-override [no issue]
  @ornikar/eslint-config-react/stories-override.js
  @ornikar/eslint-config-typescript-react/stories-override.js
Labels: :ok_hand: code/approved, frontend, :soon: automerge

#204 fix: downgrade node requirement [no issue]
  @ornikar/eslint-config-babel/package.json
  @ornikar/eslint-config-formatjs/package.json
  @ornikar/eslint-config-react/package.json
  @ornikar/eslint-config-typescript-react/package.json
  @ornikar/eslint-config-typescript/package.json
  @ornikar/eslint-config/package.json
Labels: :ok_hand: code/approved, frontend, :soon: automerge

#211 fix: disable unicorn/prefer-at [no issue]
  @ornikar/eslint-config-typescript/tests/prefer-string-starts-ends-with.ts
  @ornikar/eslint-config/rules/unicorn.js
  @ornikar/eslint-config/tests/prefer-at.js
Labels: :ok_hand: code/approved, frontend, :soon: automerge

#213 feat(eslint-config): enable unicorn/no-useless-spread [no issue]
  @ornikar/eslint-config/rules/unicorn.js
  @ornikar/eslint-config/tests/no-useless-spread.js
Labels: :ok_hand: code/approved, frontend

#215 feat(eslint-config): enable unicorn/no-useless-length-check [no issue]
  @ornikar/eslint-config/rules/unicorn.js
  @ornikar/eslint-config/tests/no-useless-length-check.js
Labels: :ok_hand: code/approved, frontend
