Repository ornikar/eslint-configs, pull requests merged in 2022-08, with the labels that each got.

#370 feat(eslint-config-typscript): add consistent-generic-constructors [no issue]
  @ornikar/eslint-config-typescript/rules/typescript-eslint.js
  @ornikar/eslint-config-typescript/tests/consistent-generic-constructors.ts
Labels: :ok_hand: code/approved, frontend

#369 feat(jsx-curly-brace-presence): removing disable [no issue]
  @ornikar/eslint-config-react/rules/react.js
  @ornikar/eslint-config-react/tests/JSXQuotes.js
Labels: :ok_hand: code/approved, frontend

#371 feat(eslint-config-typescript): enable no-duplicate-enum-values ARCH-1561
  @ornikar/eslint-config-typescript/rules/typescript-eslint.js
  @ornikar/eslint-config-typescript/tests/no-duplicate-enum-values.ts
Labels: :ok_hand: code/approved, frontend, :soon: automerge

#372 feat(eslint-config): enable text-encoding-identifier-case and prefer-json-parse-buffer ARCH-1562
  @ornikar/eslint-config/rules/unicorn.js
  @ornikar/eslint-config/tests/prefer-json-parse-buffer.js
  @ornikar/eslint-config/tests/text-encoding-identifier-case.js
Labels: :ok_hand: code/approved, frontend, :soon: automerge

#381 feat(eslint-config): add forbid-component-props for data-testid INS-1880
  @ornikar/eslint-config-react/rules/react-native.js
  @ornikar/eslint-config-react/tests/react-native/.eslintrc.json
  @ornikar/eslint-config-react/tests/react-native/forbid-component-props.js
Labels: :ok_hand: code/approved, frontend

#383 feat(eslint-config-typescript-nestjs): initial setup [no issue]
  .vscode/eslint-configs.code-workspace
  .yarn/cache/eslint-plugin-prefer-arrow-functions-npm-3.1.4-d3a9782c2e-581f1be4ea.zip
  @ornikar/eslint-config-babel/package.json
  @ornikar/eslint-config-formatjs/package.json
  @ornikar/eslint-config-react/package.json
  @ornikar/eslint-config-typescript-nestjs/.eslintrc.json
  @ornikar/eslint-config-typescript-nestjs/.npmignore
  @ornikar/eslint-config-typescript-nestjs/.vscode/settings.json
  @ornikar/eslint-config-typescript-nestjs/README.md
  @ornikar/eslint-config-typescript-nestjs/index.js
  @ornikar/eslint-config-typescript-nestjs/package.json
  @ornikar/eslint-config-typescript-nestjs/rules/typescript-eslint.js
  @ornikar/eslint-config-typescript-react/package.json
  @ornikar/eslint-config-typescript/package.json
  @ornikar/eslint-config/package.json
  README.md
  package.json
  yarn.lock
Labels: :ok_hand: code/approved, backend
