Repository ornikar/eslint-configs, pull requests merged in 2022-01, with the labels that each got.

#218 feat(eslint-config-typescript): import/no-default-export as error [no issue]
  @ornikar/eslint-config-typescript/rules/import.js
Labels: :ok_hand: code/approved, frontend, :soon: automerge

#219 fix(eslint-config-typescript): boolean prefix styled-components transient properties [no issue]
  @ornikar/eslint-config-typescript/rules/typescript-eslint.js
  @ornikar/eslint-config-typescript/tests/naming-convention.ts
Labels: :ok_hand: code/approved, frontend, :soon: automerge

#183 feat: use jsx-runtime [no issue]
  @ornikar/eslint-config-react/rules/react.js
  @ornikar/eslint-config-react/tests/ComponentWithTestId.js
  @ornikar/eslint-config-react/tests/JSXQuotes.js
  @ornikar/eslint-config-react/tests/Typography.js
  @ornikar/eslint-config-typescript-react/tests/App.tsx
  @ornikar/eslint-config-typescript-react/tests/react.tsx
Labels: :ok_hand: code/approved, frontend, :soon: automerge, :warning: Breaking Changes

#224 feat: add naming convention on parameters DR-1800
  @ornikar/eslint-config-typescript/rules/typescript-eslint.js
  @ornikar/eslint-config-typescript/tests/naming-convention.ts
Labels: :ok_hand: code/approved, frontend
